# Generated by Django 2.2.6 on 2020-03-26 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_userinfo_ctime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
