# Generated by Django 2.2.6 on 2020-03-27 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200326_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ctime',
            field=models.DateField(auto_now_add=True),
        ),
    ]
