# Generated by Django 2.2 on 2019-08-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_hostsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('network_name', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('site', models.CharField(max_length=32)),
                ('mem_total', models.CharField(max_length=32)),
                ('cpu_info', models.CharField(max_length=128)),
                ('disk_info', models.CharField(max_length=128)),
            ],
        ),
    ]
