# Generated by Django 2.2 on 2019-08-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190827_1008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostsinfo',
            old_name='mem_info',
            new_name='mem_total',
        ),
    ]
