# Generated by Django 2.2 on 2019-08-27 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190827_1026'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostsInfo',
        ),
    ]
