# Generated by Django 2.2 on 2019-08-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190827_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsinfo',
            name='cpu',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostsinfo',
            name='main_board',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostsinfo',
            name='memory',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hostsinfo',
            name='nic',
            field=models.TextField(),
        ),
    ]
