# Generated by Django 2.2 on 2019-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20190828_1155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostsInfo',
        ),
    ]
