# Generated by Django 2.2 on 2019-08-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_hostsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsinfo',
            name='unique_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
