# Generated by Django 2.2 on 2019-09-06 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_auto_20190906_1633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostdisk',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostloadavg',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostmem',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostnic',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hostswap',
            name='host',
        ),
        migrations.RemoveField(
            model_name='hosttasks',
            name='host',
        ),
        migrations.DeleteModel(
            name='HostCpu',
        ),
        migrations.DeleteModel(
            name='HostDisk',
        ),
        migrations.DeleteModel(
            name='HostLoadavg',
        ),
        migrations.DeleteModel(
            name='HostMem',
        ),
        migrations.DeleteModel(
            name='HostNic',
        ),
        migrations.DeleteModel(
            name='HostSwap',
        ),
        migrations.DeleteModel(
            name='HostTasks',
        ),
    ]
