# Generated by Django 2.2 on 2019-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_hostcpu_hostdisk_hostloadavg_hostmem_hostnic_hostswap_hosttasks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostcpu',
            name='ctime',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostdisk',
            name='ctime',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostloadavg',
            name='ctime',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostmem',
            name='ctime',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostnic',
            name='ctime',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hostswap',
            name='ctime',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='hosttasks',
            name='ctime',
            field=models.BigIntegerField(),
        ),
    ]
