# Generated by Django 2.2 on 2019-08-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=32)),
                ('IP', models.CharField(max_length=32)),
                ('version', models.CharField(max_length=64)),
                ('site', models.CharField(max_length=32)),
                ('cpu_cores', models.IntegerField()),
                ('mem_total', models.CharField(max_length=32)),
                ('network_name', models.CharField(max_length=32)),
                ('disk_info', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
            ],
        ),
    ]
