# Generated by Django 2.2 on 2019-08-27 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hostsinfo',
            old_name='IP',
            new_name='ip',
        ),
    ]
