# Generated by Django 2.2 on 2019-08-27 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_hostsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os_version', models.CharField(max_length=64)),
                ('hostname', models.CharField(max_length=32)),
                ('ip', models.CharField(max_length=32)),
                ('cpu', models.CharField(max_length=128)),
                ('disk', models.CharField(max_length=256)),
                ('main_board', models.CharField(max_length=128)),
                ('memory', models.CharField(max_length=64)),
                ('nic', models.CharField(max_length=256)),
            ],
        ),
    ]
