# Generated by Django 2.2 on 2019-08-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190827_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsinfo',
            name='ip',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
