# Generated by Django 2.2 on 2019-08-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_delete_hostsinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=32)),
                ('os_version', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=32, unique=True)),
                ('hostname', models.CharField(max_length=32)),
                ('cpu', models.TextField()),
                ('disk', models.TextField()),
                ('main_board', models.TextField()),
                ('memory', models.TextField()),
                ('nic', models.TextField()),
            ],
        ),
    ]
