# Generated by Django 2.2 on 2019-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_hostconn_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostconn',
            name='unique_id',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
