# Generated by Django 2.2 on 2019-09-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_auto_20190829_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=32)),
                ('running', models.CharField(max_length=32)),
                ('sleeping', models.CharField(max_length=32)),
                ('stopped', models.CharField(max_length=32)),
                ('zombie', models.CharField(max_length=32)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
    ]
