# Generated by Django 2.2 on 2019-09-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_hostloadavg'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('us', models.CharField(max_length=32)),
                ('sy', models.CharField(max_length=32)),
                ('ni', models.CharField(max_length=32)),
                ('idle', models.CharField(max_length=32)),
                ('wa', models.CharField(max_length=32)),
                ('hi', models.CharField(max_length=32)),
                ('si', models.CharField(max_length=32)),
                ('st', models.CharField(max_length=32)),
                ('util', models.CharField(max_length=32)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
    ]
