# Generated by Django 2.2 on 2019-09-06 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20190906_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=32)),
                ('running', models.CharField(max_length=32)),
                ('sleeping', models.CharField(max_length=32)),
                ('stopped', models.CharField(max_length=32)),
                ('zombie', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=32)),
                ('util', models.CharField(max_length=32)),
                ('used', models.CharField(max_length=32)),
                ('avail', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostNic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iface', models.CharField(max_length=32)),
                ('rxpcks', models.CharField(max_length=32)),
                ('txpcks', models.CharField(max_length=32)),
                ('rxkbs', models.CharField(max_length=32)),
                ('txkbs', models.CharField(max_length=32)),
                ('rxcmps', models.CharField(max_length=32)),
                ('txcmps', models.CharField(max_length=32)),
                ('rxmcsts', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostMem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.CharField(max_length=32)),
                ('used', models.CharField(max_length=32)),
                ('buffcache', models.CharField(max_length=32)),
                ('util', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostLoadavg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('one', models.CharField(max_length=32)),
                ('five', models.CharField(max_length=32)),
                ('fifteen', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostDisk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=32)),
                ('rs', models.CharField(max_length=32)),
                ('ws', models.CharField(max_length=32)),
                ('rkBs', models.CharField(max_length=32)),
                ('wkBs', models.CharField(max_length=32)),
                ('io_util', models.CharField(max_length=32)),
                ('total', models.CharField(max_length=32)),
                ('used', models.CharField(max_length=32)),
                ('size_util', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
        migrations.CreateModel(
            name='HostCpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('util', models.CharField(max_length=32)),
                ('ctime', models.DateTimeField(auto_now_add=True)),
                ('host', models.ForeignKey(on_delete=True, to='app.HostsInfo')),
            ],
        ),
    ]
