# Generated by Django 2.2 on 2019-08-27 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190827_0937'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HostsInfo',
        ),
    ]
