# Generated by Django 2.2 on 2019-08-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_hostsinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostsinfo',
            name='ip',
        ),
    ]
