# Generated by Django 2.2 on 2019-08-27 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_hostsinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostsinfo',
            name='disk',
            field=models.TextField(),
        ),
    ]
