# Generated by Django 2.2 on 2019-08-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20190828_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostConn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=32)),
                ('port', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('unique_id', models.CharField(max_length=32)),
            ],
        ),
    ]
