# Generated by Django 2.2 on 2019-08-29 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20190829_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostconn',
            name='unique_id',
            field=models.CharField(default=1, max_length=32),
            preserve_default=False,
        ),
    ]
