# Generated by Django 2.2.6 on 2020-03-23 06:58

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=128, unique=True)),
                ('project_name', models.CharField(default=None, max_length=64)),
                ('property_area', models.CharField(default=None, max_length=64)),
                ('account', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.account')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16, verbose_name='部门名称')),
            ],
        ),
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platname', models.CharField(default=None, max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('email', models.CharField(max_length=32, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=16, verbose_name='姓名')),
                ('phone', models.CharField(max_length=32, verbose_name='手机号')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.Department', verbose_name='部门')),
                ('roles', models.ManyToManyField(blank=True, to='rbac.Role', verbose_name='拥有的所有角色')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='hosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_id', models.CharField(max_length=128, unique=True)),
                ('hostname', models.CharField(default=None, max_length=64)),
                ('pri_ip', models.CharField(max_length=32, unique=True)),
                ('pub_ip', models.CharField(max_length=32, unique=True)),
                ('status', models.CharField(default=None, max_length=32)),
                ('image_name', models.CharField(default=None, max_length=32)),
                ('memory', models.IntegerField(default=None)),
                ('cpu', models.SmallIntegerField(default=None)),
                ('ctime', models.DateTimeField(default=None)),
                ('volume_list', models.TextField(default=None)),
                ('account', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.account')),
                ('area', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.area', to_field='project_id')),
                ('item', models.ForeignKey(default=1, on_delete=django.db.models.expressions.Case, to='api.item')),
                ('platform', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.platform')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.platform'),
        ),
    ]
