# Generated by Django 2.2.6 on 2020-03-28 04:03

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200327_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(default=None, max_length=32, verbose_name='账号名称'),
        ),
        migrations.AlterField(
            model_name='area',
            name='project_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='区域id'),
        ),
        migrations.AlterField(
            model_name='area',
            name='project_name',
            field=models.CharField(default=None, max_length=64, verbose_name='区域英文名称'),
        ),
        migrations.AlterField(
            model_name='area',
            name='property_area',
            field=models.CharField(default=None, max_length=64, verbose_name='区域中文'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='cpu',
            field=models.SmallIntegerField(default=None, verbose_name='cpu大小'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='ctime',
            field=models.DateTimeField(default=None, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='host_id',
            field=models.CharField(max_length=128, unique=True, verbose_name='主机id'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='hostname',
            field=models.CharField(default=None, max_length=64, verbose_name='主机名称'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='image_name',
            field=models.CharField(default=None, max_length=32, verbose_name='镜像名称'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.item'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='memory',
            field=models.IntegerField(default=None, verbose_name='内存大小'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='pri_ip',
            field=models.CharField(max_length=32, unique=True, verbose_name='主机内网IP'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='pub_ip',
            field=models.CharField(max_length=32, unique=True, verbose_name='主机公网IP'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='status',
            field=models.CharField(default=None, max_length=32, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='hosts',
            name='volume_list',
            field=models.TextField(default=None, verbose_name='磁盘列表'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemname',
            field=models.CharField(default=None, max_length=32, verbose_name='项目名称'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platname',
            field=models.CharField(default=None, max_length=32, verbose_name='平台名称'),
        ),
        migrations.CreateModel(
            name='dbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=128, unique=True, verbose_name='数据库id')),
                ('dbname', models.CharField(default=None, max_length=64, verbose_name='数据库名称')),
                ('type', models.CharField(max_length=32, verbose_name='数据库类型')),
                ('mode', models.CharField(max_length=32, verbose_name='数据库架构类型')),
                ('pri_ip', models.CharField(max_length=32, unique=True, verbose_name='内网IP')),
                ('pub_ip', models.CharField(default=None, max_length=32, verbose_name='公网IP')),
                ('status', models.CharField(default=None, max_length=32, verbose_name='状态')),
                ('version', models.CharField(default=None, max_length=32, verbose_name='版本')),
                ('memory', models.IntegerField(default=None, verbose_name='内存大小')),
                ('cpu', models.SmallIntegerField(default=None, verbose_name='cpu大小')),
                ('ctime', models.DateTimeField(default=None, verbose_name='创建时间')),
                ('disk', models.TextField(default=None, verbose_name='磁盘大小')),
                ('account', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.account')),
                ('area', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.area', to_field='project_id')),
                ('item', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.item')),
                ('platform', models.ForeignKey(on_delete=django.db.models.expressions.Case, to='api.platform')),
            ],
        ),
    ]
