# Generated by Django 2.2.6 on 2020-03-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200328_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbs',
            name='cpu',
            field=models.CharField(default=None, max_length=32, verbose_name='cpu大小'),
        ),
        migrations.AlterField(
            model_name='dbs',
            name='disk',
            field=models.CharField(default=None, max_length=32, verbose_name='磁盘大小'),
        ),
    ]
